export const mockCandidates = [
  { id: '1', name: 'John Doe', contact: '999-302-33-44', email: 'johhny@mail.com' },
  { id: '2', name: 'Mary Moser', contact: '923-312-76-41', email: 'marrym@mail.com' },
  { id: '3', name: 'Elijah Cruz', contact: '902-304-99-16', email: 'e.cruz@mail.com' },
  { id: '4', name: 'Liam Morales', contact: '111-334-99-16', email: 'morales22@mail.com' },
];

export const mockEmployees = [
  {
    id: '333',
    name: 'Tom',
    lastName: 'Carr',
    userImage: '',
    dob: '11/01/1989',
    city: 'Kyiv',
    email: 'tomcarr@mail.com',
    contact: '111-334-99-16',
    emergencyContact: { name: 'Arnold', contact: '111-334-99-16', relation: 'Friend' },
    position: 'manager',
    initialHireDate: '',
    terminationDate: '',
  },
  {
    id: '222',
    name: 'Lucas',
    lastName: 'Yen',
    userImage: '',
    dob: '23/01/1989',
    city: 'Odessa',
    email: 'lucas13@mail.com',
    contact: '121-324-99-36',
    emergencyContact: { name: 'Tina', contact: '113-334-99-16', relation: 'Spouse' },
    position: 'dispatch',
    initialHireDate: '',
    terminationDate: '',
  },
  {
    id: '444',
    name: 'Andy',
    lastName: 'Paz',
    userImage: '',
    dob: '23/01/1999',
    city: 'Odessa',
    email: 'andy123@mail.com',
    contact: '321-324-99-36',
    emergencyContact: { name: 'Ronald', contact: '133-334-99-16', relation: 'Father' },
    position: 'customer support',
    initialHireDate: '',
    terminationDate: '',
  },
  {
    id: '555',
    name: 'Amy',
    lastName: 'Nickel',
    userImage: '',
    dob: '23/01/1993',
    city: 'Kyiv',
    email: 'amyyy2@mail.com',
    contact: '421-324-99-36',
    emergencyContact: { name: 'Natan', contact: '133-354-99-16', relation: 'Brother' },
    position: 'sales',
    initialHireDate: '',
    terminationDate: '',
  },
  {
    id: '313',
    name: 'Stanley',
    lastName: 'Forbs',
    userImage: '',
    dob: '31/04/1993',
    city: 'Lviv',
    email: 'staan88@mail.com',
    contact: '421-324-99-36',
    emergencyContact: { name: 'Nancy', contact: '133-354-99-16', relation: 'Spouse' },
    position: 'sales',
    initialHireDate: '',
    terminationDate: '',
  },
];

export const mockAccounts = [
  { name: 'Notebooks', category: 'Office goods', createdAt: '', budget: '1000', spend: '600', rest: '400' },
  { name: '5 LG displays', category: 'Office assets', createdAt: '', budget: '13000', spend: '12800', rest: '200' },
  { name: '1 kg Coffee', category: 'Provision', createdAt: '', budget: '300', spend: '300', rest: '0' },
];

export const mockUser = { name: 'RodneyHr', createdAt: '', role: 'hr' };
